# Generated by Django 5.2.17 on 2026-10-02 08:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifyIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.UUIDField()),
                ('app_code', models.CharField(max_length=128)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DifyPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_digest', models.CharField(max_length=64)),
                ('token_digest', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.botgrant')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.difyidentity')),
            ],
        ),
        migrations.AddConstraint(
            model_name='difyidentity',
            constraint=models.UniqueConstraint(fields=('user', 'bot', 'app_id', 'app_code'), name='unique_dify_identity'),
        ),
        migrations.AddConstraint(
            model_name='difypassport',
            constraint=models.UniqueConstraint(fields=('grant', 'identity', 'session_digest', 'token_digest'), name='unique_dify_passport'),
        ),
    ]
